### ISSUE TITLE
Account deletion

### ISSUE THREAD

**Issue by dreid3** [dreid3/York-Engineering-Society-Website-2.0#12]
User should be able to delete their account if they are already logged in. This should be under account settings and should display a prompt asking if the user is sure they want to delete their account before deleting it.

Milestone: 50% working system

**Comment by RcVincent** [comment]
I will look into this. right now we might just keep accounts inactive so that members can immediately rejoin and not have to go through the signup process

**Comment by dreid3** [comment]
Users are now able to delete their account with a button.
