### ISSUE TITLE
Manual Email Reminder

### ISSUE THREAD

**Issue by dreid3** [dreid3/York-Engineering-Society-Website-2.0#4]
If the user is an admin, they should be able to send out an email to all users with anything they in it directly from the site. User can choose a time / date for the mass email reminder to be sent. User can also choose specifically which users they want to receive the email reminder, such as sending reminders only to those who have specifically chosen to subscribe to an event.

Milestone: Final working system

**Comment by RcVincent** [comment]
I will take ownership of this for now but I might require assistance in the future

**Comment by dreid3** [comment]
They can not choose a time / date. This is mostly done, except they can not choose specific users because I'm unsure of how they would want that.
